/* 
  -- DO NOT EDIT THIS FILE
*/

import scansJson from '../../db/scans.json';
import { Scan, DateRange } from './scan.types';

export class ScanRepository {
  private static scans: Scan[] = scansJson;

  static findAll(dateRange?: DateRange, cloudProviderId?: string): Promise<Scan[]> {
    let filteredScans = this.scans;

    if (dateRange) {
      filteredScans = filteredScans.filter(scan => {
        const scanDate = new Date(scan.date);
        return scanDate >= dateRange.startDate && scanDate <= dateRange.endDate;
      });
    }

    if (cloudProviderId) {
      filteredScans = filteredScans.filter(scan => scan.cloudProviderId === cloudProviderId);
    }

    return Promise.resolve(filteredScans);
  }
}
